# oh-my-zsh 安装
#sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

plugins=(zsh-autosuggestions autojump)

# 插件安装
# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
# brew install autojump

source $ZSH/oh-my-zsh.sh

# 防止重复的history
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP
setopt inc_append_history
setopt share_history

# Fzf history Ctrl+R 快捷键
source /usr/local/opt/fzf/shell/key-bindings.zsh


# 环境变量, Path相关配置
export http_proxy=127.0.0.1:1087
export https_proxy=127.0.0.1:1087
export JAVA_HOME=/usr/lib/jvm/default-java

export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
export PATH="/usr/local/opt/mongodb@3.6/bin/:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="/opt/bin:$PATH"

export GO11MODULE=on
unset GOROOT
export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib:$DYLD_LIBRARY_PATH
# ANDROID
export PATH="/usr/local/opt/openjdk/bin:$PATH"
alias task="asynctask -f"
export PYENV_ROOT="$HOME/.pyenv"
export PATH=$PYENV_ROOT/shims:$PATH
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/opt/t/google-cloud-sdk/path.zsh.inc' ]; then . '/opt/t/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/opt/t/google-cloud-sdk/completion.zsh.inc' ]; then . '/opt/t/google-cloud-sdk/completion.zsh.inc'; fi

ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}"

